# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7290999d0584053f2efc11b17897afbb285a0d73fc48a12eb7278125a15827b1de62d90166fe23feaa68188e59428f16586d89059594874d65081e9799b0451e

test:
  secret_key_base: 2e65637aed17e2c8eedf63842dff0859af5de6fd5fbc59c9242a43056796172f2249ccccf3786ee91ab347f4f08d28078c9bf241007558413c831ed108565e23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
